---
resources:
- name: resource-git
  type: git
  source:
    uri: https://github.com/sharethemagics/test.git


jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-git
  
  - task: web-app-tests
    file: resource-git/run_test.yml